// <auto-generated />
using System;
using AirBB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBB.Migrations
{
    [DbContext(typeof(AirBnBContext))]
    [Migration("20251021163734_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirBB.Models.Client", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AirBB.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "Chicago"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Miami"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Atlanta"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<string>("ClientUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidenceId"));

                    b.Property<int>("BathroomNumber")
                        .HasColumnType("int");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("int");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResidencePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 101,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            GuestNumber = 3,
                            LocationId = 1,
                            Name = "Chicago Loop Apartment",
                            PricePerNight = 120m,
                            ResidencePicture = "chi_loop.jpg"
                        },
                        new
                        {
                            ResidenceId = 102,
                            BathroomNumber = 1,
                            BedroomNumber = 0,
                            GuestNumber = 2,
                            LocationId = 2,
                            Name = "NYC Cozy Studio",
                            PricePerNight = 150m,
                            ResidencePicture = "nyc_studio.jpg"
                        },
                        new
                        {
                            ResidenceId = 103,
                            BathroomNumber = 2,
                            BedroomNumber = 3,
                            GuestNumber = 6,
                            LocationId = 3,
                            Name = "Miami Beach House",
                            PricePerNight = 320m,
                            ResidencePicture = "miami_beach.jpg"
                        },
                        new
                        {
                            ResidenceId = 104,
                            BathroomNumber = 2,
                            BedroomNumber = 3,
                            GuestNumber = 5,
                            LocationId = 4,
                            Name = "Atlanta Suburban Single Family House",
                            PricePerNight = 180m,
                            ResidencePicture = "atl_house.jpg"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Reservation", b =>
                {
                    b.HasOne("AirBB.Models.Residence", "Residence")
                        .WithMany("Reservations")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.HasOne("AirBB.Models.Location", "Location")
                        .WithMany("Residences")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AirBB.Models.Location", b =>
                {
                    b.Navigation("Residences");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
