// <auto-generated />
using System;
using AirBB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBB.Migrations
{
    [DbContext(typeof(AirBnBContext))]
    partial class AirBnBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AirBB.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Email = "clientA@mail.com",
                            Name = "Client A",
                            PhoneNumber = "9999999999"
                        },
                        new
                        {
                            ClientId = 2,
                            Email = "clientB@mail.com",
                            Name = "Client B",
                            PhoneNumber = "8888888888"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "Chicago"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Miami"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Atlanta"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            ClientUserId = 1,
                            ReservationEndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 101
                        },
                        new
                        {
                            ReservationId = 2,
                            ClientUserId = 2,
                            ReservationEndDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 103
                        });
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accommodation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BathroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bathrooms")
                        .HasColumnType("TEXT");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuiltYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 101,
                            Accommodation = 3,
                            BathroomNumber = 0,
                            Bathrooms = 1m,
                            BedroomNumber = 0,
                            Bedrooms = 1,
                            BuiltYear = 2000,
                            GuestNumber = 0,
                            ImageFileName = "chi_loop.jpg",
                            LocationId = 1,
                            Name = "Chicago Loop Apartment",
                            OwnerId = 201,
                            PricePerNight = 120m
                        },
                        new
                        {
                            ResidenceId = 102,
                            Accommodation = 2,
                            BathroomNumber = 0,
                            Bathrooms = 1m,
                            BedroomNumber = 0,
                            Bedrooms = 0,
                            BuiltYear = 2005,
                            GuestNumber = 0,
                            ImageFileName = "nyc_studio.jpg",
                            LocationId = 2,
                            Name = "NYC Cozy Studio",
                            OwnerId = 202,
                            PricePerNight = 150m
                        },
                        new
                        {
                            ResidenceId = 103,
                            Accommodation = 6,
                            BathroomNumber = 0,
                            Bathrooms = 2m,
                            BedroomNumber = 0,
                            Bedrooms = 3,
                            BuiltYear = 1998,
                            GuestNumber = 0,
                            ImageFileName = "miami_beach.jpg",
                            LocationId = 3,
                            Name = "Miami Beach House",
                            OwnerId = 203,
                            PricePerNight = 320m
                        },
                        new
                        {
                            ResidenceId = 104,
                            Accommodation = 5,
                            BathroomNumber = 0,
                            Bathrooms = 2m,
                            BedroomNumber = 0,
                            Bedrooms = 3,
                            BuiltYear = 2010,
                            GuestNumber = 0,
                            ImageFileName = "atl_house.jpg",
                            LocationId = 4,
                            Name = "Atlanta Suburban House",
                            OwnerId = 204,
                            PricePerNight = 180m
                        });
                });

            modelBuilder.Entity("AirBB.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 201,
                            Email = "john@mail.com",
                            Name = "John Owner",
                            PhoneNumber = "1111111111",
                            SSN = "111-22-3333",
                            UserType = "Owner"
                        },
                        new
                        {
                            UserId = 202,
                            Email = "emma@mail.com",
                            Name = "Emma Owner",
                            PhoneNumber = "2222222222",
                            SSN = "444-55-6666",
                            UserType = "Owner"
                        },
                        new
                        {
                            UserId = 203,
                            Email = "mike@mail.com",
                            Name = "Michael Owner",
                            PhoneNumber = "3333333333",
                            SSN = "777-88-9999",
                            UserType = "Owner"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Reservation", b =>
                {
                    b.HasOne("AirBB.Models.Residence", "Residence")
                        .WithMany("Reservations")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.HasOne("AirBB.Models.Location", "Location")
                        .WithMany("Residences")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirBB.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AirBB.Models.Location", b =>
                {
                    b.Navigation("Residences");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
