// <auto-generated />
using System;
using AirBB.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBB.Migrations
{
    [DbContext(typeof(AirBnBContext))]
    partial class AirBnBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AirBB.Models.DomainModels.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            DOB = new DateTime(1990, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@example.com",
                            Name = "John Doe",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            ClientId = 2,
                            DOB = new DateTime(1988, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma@example.com",
                            Name = "Emma Watson",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            ClientId = 3,
                            DOB = new DateTime(1985, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chris@example.com",
                            Name = "Chris Evans",
                            PhoneNumber = "7778889999"
                        },
                        new
                        {
                            ClientId = 4,
                            DOB = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mia@example.com",
                            Name = "Mia Smith",
                            PhoneNumber = "5551237890"
                        },
                        new
                        {
                            ClientId = 5,
                            DOB = new DateTime(1995, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "liam@example.com",
                            Name = "Liam Brown",
                            PhoneNumber = "4442221111"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "New York"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Chicago"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Boston"
                        },
                        new
                        {
                            LocationId = 5,
                            Name = "Miami"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            ClientUserId = 3,
                            ReservationEndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 1
                        },
                        new
                        {
                            ReservationId = 2,
                            ClientUserId = 4,
                            ReservationEndDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 2
                        },
                        new
                        {
                            ReservationId = 3,
                            ClientUserId = 5,
                            ReservationEndDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 3
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accommodation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bathrooms")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuiltYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 1,
                            Accommodation = 4,
                            Bathrooms = 1.5m,
                            Bedrooms = 2,
                            BuiltYear = 2010,
                            GuestNumber = 5,
                            ImageFileName = "atl_house.jpg",
                            LocationId = 1,
                            Name = "Central Apartment",
                            OwnerId = 1,
                            PricePerNight = 120m
                        },
                        new
                        {
                            ResidenceId = 2,
                            Accommodation = 6,
                            Bathrooms = 2m,
                            Bedrooms = 3,
                            BuiltYear = 2015,
                            GuestNumber = 3,
                            ImageFileName = "chi_loop.jpg",
                            LocationId = 2,
                            Name = "Ocean View House",
                            OwnerId = 2,
                            PricePerNight = 200m
                        },
                        new
                        {
                            ResidenceId = 3,
                            Accommodation = 2,
                            Bathrooms = 1m,
                            Bedrooms = 1,
                            BuiltYear = 2020,
                            GuestNumber = 10,
                            ImageFileName = "nyc_studio.jpg",
                            LocationId = 3,
                            Name = "City Studio",
                            OwnerId = 1,
                            PricePerNight = 90m
                        },
                        new
                        {
                            ResidenceId = 4,
                            Accommodation = 5,
                            Bathrooms = 1.5m,
                            Bedrooms = 2,
                            BuiltYear = 2018,
                            GuestNumber = 1,
                            ImageFileName = "miami_beach.jpg",
                            LocationId = 4,
                            Name = "Modern Condo",
                            OwnerId = 2,
                            PricePerNight = 150m
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "owner1@mail.com",
                            Name = "Owner One",
                            PhoneNumber = "7001002003",
                            SSN = "SSN001",
                            UserType = "Owner"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "owner2@mail.com",
                            Name = "Owner Two",
                            PhoneNumber = "7001002004",
                            SSN = "SSN002",
                            UserType = "Owner"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "clientA@mail.com",
                            Name = "Client A",
                            PhoneNumber = "7001002005",
                            SSN = "SSN003",
                            UserType = "Client"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "clientB@mail.com",
                            Name = "Client B",
                            PhoneNumber = "7001002006",
                            SSN = "SSN004",
                            UserType = "Client"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "clientC@mail.com",
                            Name = "Client C",
                            PhoneNumber = "7001002007",
                            SSN = "SSN005",
                            UserType = "Client"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Reservation", b =>
                {
                    b.HasOne("AirBB.Models.DomainModels.Residence", "Residence")
                        .WithMany("Reservations")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Residence", b =>
                {
                    b.HasOne("AirBB.Models.DomainModels.Location", "Location")
                        .WithMany("Residences")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirBB.Models.DomainModels.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Location", b =>
                {
                    b.Navigation("Residences");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Residence", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
